<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Abstractions\Base\" />
    <Folder Include="Abstractions\Interfaces\" />
    <Folder Include="Dtos\Common\" />
    <Folder Include="Dtos\Dashboard\" />
    <Folder Include="Dtos\Data\" />
    <Folder Include="Dtos\User\" />
    <Folder Include="Exceptions\" />
    <Folder Include="Responses\" />
    <Folder Include="Utilities\" />
  </ItemGroup>

</Project>
